#!/bin/bash
# This hook is run after this virtualenv is activated.

alias vman="/Users/sfishman/Documents/crimson/crimsononline/vagrant_manage.sh"
alias log="/Users/sfishman/Documents/crimson/crimsononline/showlog.sh"
alias elog="/Users/sfishman/Documents/crimson/crimsononline/showerror.sh"
alias sshprod="/Users/sfishman/Documents/crimson/sshsrv.py"
alias sshdev="/Users/sfishman/Documents/crimson/sshsrv.py -d"
export CRIMSON_NEW_RELIC_API_KEY="44d8fa8ad75d1488d0564e906625ef52e768075b2a9dadf"

