plugins=(autopep8 pep8 coffee fabric jira npm)

# support git-repo
unset gr

_goto_project_compl() {
  local repos
  repos=()

  for d in $CODE_DIRS; do
    for f in $d/*; do
      if [ -d $f ]; then
        repos+="${f##*/}"
      fi
    done
  done

  _describe "repos" repos
}

compdef _goto_project_compl goto_project

_aviator_compl() {
  local targets
  targets=($(aviator --list 2>/dev/null))
  _describe "aviator targets" targets
}

compdef _aviator_compl aviator

_ark_compl() {
  # cache ark apps 4maxspeed
  if [[ -z "$ark_apps" ]]; then
    ark_apps=($(ark apps -q))
  fi
  _describe "ark apps" ark_apps
}

compdef _ark_compl ark

